<?php
/**
 * @file
 */

require_once 'commerce_canadian_taxes.features.inc';

/**                                                                                  
 * Implementation of hook_commerce_price_formatted_components_alter()                
 * Puts the GST tax above other canadian taxes to reflect the calculation.           
 *                                                                                   
 * @param &$components                                                               
 *   The array of totaled price components.                                          
 *                                                                                   
 * @see commerce_price_field_formatter_view()                                        
 */                                                                                  
function commerce_canadian_taxes_commerce_price_formatted_components_alter(&$components) {
  // Put the GST below Subtotal (-50)                                                
  // and above other taxes (0)
  // if its current weight differs from 0                                            
  if (empty($components['tax|gst']['weight'])) {                                     
    $components['tax|gst']['weight'] = -1;
  } 
} 

