<?php
/**
 * @file
 * oic_taxonomie_contexte_geographique.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function oic_taxonomie_contexte_geographique_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Zambie',
    'description' => NULL,
    'format' => NULL,
    'weight' => '6',
    'uuid' => '0048850f-6df4-45fc-bbe6-139957e352f5',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Bogota',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0143a7b6-5e52-424b-a4dc-31532cb84ab1',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '2bc97af0-f9a6-43c9-aa49-c1b606abcb9f',
    ),
  );
  $terms[] = array(
    'name' => 'Palerme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '01c4e5b0-17f3-40be-aba9-3ae5807d6fd9',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '64eab00c-a563-4cd4-963c-ce4be915f6c9',
    ),
  );
  $terms[] = array(
    'name' => 'Fukuyama',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '024bf0b8-641e-4d24-b4cf-857499135831',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '217c146b-1efb-4189-a84d-da605e3fc1e3',
    ),
  );
  $terms[] = array(
    'name' => 'Rio de Janeiro',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '02bf4f06-d5d8-4757-904d-5d705364ed1c',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '3fdd3534-6d74-4c02-aa9b-45e02503c77d',
    ),
  );
  $terms[] = array(
    'name' => 'Florence',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '02d6b815-d8a4-4772-8a19-d8de21a7b126',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '64eab00c-a563-4cd4-963c-ce4be915f6c9',
    ),
  );
  $terms[] = array(
    'name' => 'Afrique',
    'description' => '',
    'format' => 'html',
    'weight' => '-13',
    'uuid' => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
  );
  $terms[] = array(
    'name' => 'Haïti',
    'description' => '',
    'format' => 'html',
    'weight' => '-2',
    'uuid' => '03bb0fa2-eb93-4d08-b6f2-5df72adf4857',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'a327d8ca-46ff-4ae5-a913-42777dbc9fcb',
    ),
  );
  $terms[] = array(
    'name' => 'Los Angeles',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0547742c-52db-4ecf-901a-5f86fa309465',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fabd48c5-4b2e-488b-8ae9-c70a320ff0c2',
    ),
  );
  $terms[] = array(
    'name' => 'Slovaquie',
    'description' => NULL,
    'format' => NULL,
    'weight' => '14',
    'uuid' => '06a26012-163c-4918-b456-df467a314b8c',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Québec',
    'description' => '',
    'format' => 'html',
    'weight' => '2',
    'uuid' => '07c34c74-6e96-41f3-ae09-cf1e540f338e',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '7d948fcb-bf1a-455b-aa35-71435dbf1db1',
    ),
  );
  $terms[] = array(
    'name' => 'Jérusalem',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-9',
    'uuid' => '080f7316-3162-4021-a4c9-ab9de5de6e4c',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Pays-Bas',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-2',
    'uuid' => '0872d081-dcd4-4cf6-99ee-a4862511f68e',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Hongrie',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-7',
    'uuid' => '09562c69-1fcb-4902-a3e9-2121ff8d985f',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'La Havane',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0990bc05-9e85-42b3-914a-e38f6da87f5e',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '909af47c-fc1a-48d4-8583-afdf06e54368',
    ),
  );
  $terms[] = array(
    'name' => 'Afghanistan',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-21',
    'uuid' => '09e285ca-8eb2-44e4-a15a-70dd0f5cc6b0',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Kiev',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0b2d95f8-fd73-408a-9ddd-dfde1cc07401',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'b19fc95f-5d3c-40a2-acfa-200ebea16b5f',
    ),
  );
  $terms[] = array(
    'name' => 'Vancouver',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0c25435e-f7b8-47db-9e64-84c9e4b75c80',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '7d948fcb-bf1a-455b-aa35-71435dbf1db1',
    ),
  );
  $terms[] = array(
    'name' => 'Tripoli',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0c47b542-ef79-4e0c-ab8f-ef64fdb3af1e',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '6ba2f980-fca6-479e-8084-3c92fa5551e8',
    ),
  );
  $terms[] = array(
    'name' => 'Irlande',
    'description' => '',
    'format' => 'html',
    'weight' => '-6',
    'uuid' => '0d56338b-3373-45a4-8267-1eaaa1d809ea',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Oulan-Bator',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0e4d268d-d759-407a-8967-c50ed4894a0b',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '59134f7e-600b-4783-932c-d12991c96e62',
    ),
  );
  $terms[] = array(
    'name' => 'Portugal',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-2',
    'uuid' => '110f9619-f29f-4321-98cd-789419c3026a',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Tijuana',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '12cc9695-b2da-4fd9-84d8-4c748933190e',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'c889463d-64b5-4942-93f1-e8e39a315354',
    ),
  );
  $terms[] = array(
    'name' => 'La Paz',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '190fdc95-cd9c-4838-bc9a-17442ce946df',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '840ac2f7-fc9f-4995-8058-607718fd4c57',
    ),
  );
  $terms[] = array(
    'name' => 'Mozambique',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-5',
    'uuid' => '1a024a34-912c-4eed-9908-5d2abe2f273d',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Séville',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1a100b75-a207-4fac-bf77-77bcb9bb19e7',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'a7ede740-480c-49db-9297-82cc51c0e322',
    ),
  );
  $terms[] = array(
    'name' => 'Lesotho',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-11',
    'uuid' => '1a7f5572-a430-4279-bf68-065d73040ff2',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Delhi',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1bab0a8c-7527-4d60-aad5-31b8eef0e284',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '1dedfa2a-d780-4793-babb-2bbe0db33451',
    ),
  );
  $terms[] = array(
    'name' => 'Phnom Penh',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1cf5f66e-9d64-45d5-a511-46421d166151',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'c21b20cf-2aae-4c86-9454-b225329438ef',
    ),
  );
  $terms[] = array(
    'name' => 'Autriche',
    'description' => '',
    'format' => 'html',
    'weight' => '-17',
    'uuid' => '1d5a93b8-c179-4dc5-b76a-225509b22202',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Inde',
    'description' => '',
    'format' => 'html',
    'weight' => '-14',
    'uuid' => '1dedfa2a-d780-4793-babb-2bbe0db33451',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Serbie',
    'description' => NULL,
    'format' => NULL,
    'weight' => '8',
    'uuid' => '1e12936c-ad69-44e8-9e95-34a3e3af02cd',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Pérou',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1e31833b-f6a0-4e97-af67-289ee82c58d6',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fc9f4031-1a62-4e3a-9f90-9b2192dd5b21',
    ),
  );
  $terms[] = array(
    'name' => 'Libye',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-10',
    'uuid' => '1f3ffce5-f4b8-4b2e-a56a-0c2dc3007189',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Louvain',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1f51666d-9081-4a5b-a36f-f4883656f2f0',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '92f5c202-87eb-4af0-9c37-cca07b03b160',
    ),
  );
  $terms[] = array(
    'name' => 'Vienne',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1fbbda92-73dc-4182-b60b-2224c13394eb',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '1d5a93b8-c179-4dc5-b76a-225509b22202',
    ),
  );
  $terms[] = array(
    'name' => 'Santa Cruz',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1fee0e07-8876-4c6b-8a21-b87c48cc119c',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '840ac2f7-fc9f-4995-8058-607718fd4c57',
    ),
  );
  $terms[] = array(
    'name' => 'Japon',
    'description' => '',
    'format' => 'html',
    'weight' => '-10',
    'uuid' => '217c146b-1efb-4189-a84d-da605e3fc1e3',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'République de Slovénie',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-1',
    'uuid' => '23d61b6b-ece1-4c27-ae4f-40b2c189aaee',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Lodz',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '25f9ebae-c8b4-405b-b1d2-24300bf42d6d',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '5e125aec-bcc1-4c3a-9b36-e795cb512454',
    ),
  );
  $terms[] = array(
    'name' => 'Mumbai',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '269999ae-304a-4e89-a4ba-81e31f468f8f',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '1dedfa2a-d780-4793-babb-2bbe0db33451',
    ),
  );
  $terms[] = array(
    'name' => 'Berlin',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '27104054-98b0-4f9a-8faa-45c8b8c100cb',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '7af0a5f7-5388-418f-891b-055e2efcfac5',
    ),
  );
  $terms[] = array(
    'name' => 'Shanghai',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '279fc5f3-1332-4b57-b933-ec4e96551b7b',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'bd97a16a-651f-48c1-a91e-753e00127658',
    ),
  );
  $terms[] = array(
    'name' => 'Nigéria',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-3',
    'uuid' => '27c22c3a-a063-44ce-a59c-e334a19564d9',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Odense',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '27dead99-c735-4cbb-89eb-8da8ba493ed8',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '580467d3-e6a8-4052-b07b-ada40777bedc',
    ),
  );
  $terms[] = array(
    'name' => 'Tunisie',
    'description' => '',
    'format' => 'html',
    'weight' => '5',
    'uuid' => '289881a4-3acf-46dc-bc3a-daa5ccb98257',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Liverpool',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '28ae7661-a9ec-4610-b4b0-b1f56648458a',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '882938b0-0c38-4e4a-a975-e6270cae9b28',
    ),
  );
  $terms[] = array(
    'name' => 'Indochine française',
    'description' => '',
    'format' => 'html',
    'weight' => '-13',
    'uuid' => '296423c1-572e-4413-9dbb-9cef9c1700ea',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Dubrovnik',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '29d0b3f0-12ee-4e8f-a049-66ef6ee1a4f0',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'a9fbc80a-b60b-4015-b025-38a46639331d',
    ),
  );
  $terms[] = array(
    'name' => 'Cordoba',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2bc2d49f-a4c3-48bc-af2e-03e0af740509',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '7bfdb7b2-8767-494e-8d33-cfcc501d5ebd',
    ),
  );
  $terms[] = array(
    'name' => 'Colombie',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2bc97af0-f9a6-43c9-aa49-c1b606abcb9f',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fc9f4031-1a62-4e3a-9f90-9b2192dd5b21',
    ),
  );
  $terms[] = array(
    'name' => 'Medellin',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2d182a57-5189-488a-98bf-2d05f48ff0e1',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '2bc97af0-f9a6-43c9-aa49-c1b606abcb9f',
    ),
  );
  $terms[] = array(
    'name' => 'Stockholm',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2e25c878-58ef-491c-8b62-06a928c9d40a',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'e56c38b9-a86f-4e5d-a28b-3963ef312000',
    ),
  );
  $terms[] = array(
    'name' => 'Chicago',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2f4b3833-19cd-4b57-8a86-e3c165870721',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fabd48c5-4b2e-488b-8ae9-c70a320ff0c2',
    ),
  );
  $terms[] = array(
    'name' => 'Zimbabwe',
    'description' => NULL,
    'format' => NULL,
    'weight' => '7',
    'uuid' => '3097ad20-cc36-45d3-9fa6-6fb3d6094869',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Hô-Chi-Ming-Ville',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '30bec241-e156-4a59-873d-b5765c84bbef',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'd3bcc6ee-f072-4573-b535-0c9e789b5267',
    ),
  );
  $terms[] = array(
    'name' => 'Niger',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-4',
    'uuid' => '31b1b16c-9c89-4a6f-a1b1-39521e509558',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Angola',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-23',
    'uuid' => '339671bc-413c-47fb-9883-c331138a35f4',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Panama',
    'description' => NULL,
    'format' => NULL,
    'weight' => '3',
    'uuid' => '3536e837-61ef-41c9-9c96-71b6754c125c',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'a327d8ca-46ff-4ae5-a913-42777dbc9fcb',
    ),
  );
  $terms[] = array(
    'name' => 'Salzbourg',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '36f27dfc-17d1-4f2d-9836-824d1deda1c4',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '1d5a93b8-c179-4dc5-b76a-225509b22202',
    ),
  );
  $terms[] = array(
    'name' => 'Népal',
    'description' => '',
    'format' => 'html',
    'weight' => '-4',
    'uuid' => '3736cc10-2c33-4549-9fdc-1a6eb8bf6c43',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Kosovo',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-4',
    'uuid' => '39112744-d22c-4f29-907d-63a31f9fbbac',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Valencia',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3b5d0cb8-b804-4b36-9db7-e939008c5b38',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'd3e34d4a-cacc-4f72-addf-a10942459aa6',
    ),
  );
  $terms[] = array(
    'name' => 'Oslo',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3c73d3c9-0783-4a16-9904-33eda1ec8a2e',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8fdc3b01-6bee-43c8-8d2c-7c647dc4cc05',
    ),
  );
  $terms[] = array(
    'name' => 'Prague',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3e2cf261-25d2-499e-b05b-31376c648ac3',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'a859c3a4-89cf-4e0d-b6ab-700fe80f33e7',
    ),
  );
  $terms[] = array(
    'name' => 'Montréal',
    'description' => NULL,
    'format' => NULL,
    'weight' => '1',
    'uuid' => '3f4dd855-8a76-4f22-a6c9-ee0c348bf620',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '7d948fcb-bf1a-455b-aa35-71435dbf1db1',
    ),
  );
  $terms[] = array(
    'name' => 'Brésil',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '3fdd3534-6d74-4c02-aa9b-45e02503c77d',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fc9f4031-1a62-4e3a-9f90-9b2192dd5b21',
    ),
  );
  $terms[] = array(
    'name' => 'Guadeloupe',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-4',
    'uuid' => '4022db14-7754-4121-8a6a-7a3618bcb0f3',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'a327d8ca-46ff-4ae5-a913-42777dbc9fcb',
    ),
  );
  $terms[] = array(
    'name' => 'Mexico',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4040f5ae-174f-463e-ac21-d2a41af1c0a5',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'c889463d-64b5-4942-93f1-e8e39a315354',
    ),
  );
  $terms[] = array(
    'name' => 'Glasgow',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '427becef-4f9d-499d-a7fe-6e6b0f4fb66e',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '7d7bd79f-3ec4-42ed-825c-adb72c6dd584',
    ),
  );
  $terms[] = array(
    'name' => 'Albanie',
    'description' => '',
    'format' => 'html',
    'weight' => '-20',
    'uuid' => '432c09d3-6bee-448f-ad43-485548d2a6ba',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Bénin',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-22',
    'uuid' => '43caac8e-c935-4eed-a8e0-3d35251e2000',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'San José',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '43f0fd86-0e8e-4f8b-ba2c-48a32f806fd6',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '9840295b-bbfc-4d11-a8e4-92a6fb11d567',
    ),
  );
  $terms[] = array(
    'name' => 'Santiago',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '44469d6a-266f-466c-991e-f896a719ecae',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'c8e776ef-3552-4b3e-a24e-636c9959f6c1',
    ),
  );
  $terms[] = array(
    'name' => 'Nouvelle-Guinée',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '45a4980a-5b5b-4a83-af29-9c974c9dea28',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ca851e3d-ae02-44f0-af36-b95fa0ef0884',
    ),
  );
  $terms[] = array(
    'name' => 'Suisse',
    'description' => '',
    'format' => 'html',
    'weight' => '18',
    'uuid' => '48b533eb-bc8f-4729-b7ee-26875fa4196c',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Katmandou',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '48bf5374-961d-4865-8056-f681e7651943',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '3736cc10-2c33-4549-9fdc-1a6eb8bf6c43',
    ),
  );
  $terms[] = array(
    'name' => 'Séoul',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '495fbeea-5faa-4de2-b95b-63ca0acfe51d',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'a296a9ab-792c-429c-9004-7714690a8d88',
    ),
  );
  $terms[] = array(
    'name' => 'Pristina',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '49d370e1-0059-4070-ba7f-2d1791e22fdd',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '39112744-d22c-4f29-907d-63a31f9fbbac',
    ),
  );
  $terms[] = array(
    'name' => 'Beyrouth',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4ad5d794-4f86-4795-b340-6ff246d25eb9',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '6ba2f980-fca6-479e-8084-3c92fa5551e8',
    ),
  );
  $terms[] = array(
    'name' => 'Antartique',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-12',
    'uuid' => '4b4ad18d-8666-4206-840d-e896dbe2b50c',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
  );
  $terms[] = array(
    'name' => 'Londres',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4c171af1-39b0-4729-9ac6-fcda4744a147',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '882938b0-0c38-4e4a-a975-e6270cae9b28',
    ),
  );
  $terms[] = array(
    'name' => 'Tokyo',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4c4a96f7-ccc8-4c65-b5b2-d7b865c38767',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '217c146b-1efb-4189-a84d-da605e3fc1e3',
    ),
  );
  $terms[] = array(
    'name' => 'Buenos Aires',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4cb0016d-fd8f-4388-9ee3-7e233962caa6',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '7bfdb7b2-8767-494e-8d33-cfcc501d5ebd',
    ),
  );
  $terms[] = array(
    'name' => 'Hambourg',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4f073da0-bde7-411a-8b2f-330e9a3eacf4',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '7af0a5f7-5388-418f-891b-055e2efcfac5',
    ),
  );
  $terms[] = array(
    'name' => 'Chemins de Compostelle',
    'description' => '',
    'format' => 'html',
    'weight' => '-15',
    'uuid' => '5197b145-693d-4d73-9f81-2f417082d63b',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Philippines',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '527805f1-ce88-49f7-b04e-e6239c687ebd',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Karachi',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '535ebeb3-b175-4de6-8235-84158746a221',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fe0aec8b-d1f4-4d84-8b52-d61ad9ab5e79',
    ),
  );
  $terms[] = array(
    'name' => 'Venise',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '538bfbd8-dba1-473d-b2bf-1ef543ad1e33',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '64eab00c-a563-4cd4-963c-ce4be915f6c9',
    ),
  );
  $terms[] = array(
    'name' => 'Soudan',
    'description' => NULL,
    'format' => NULL,
    'weight' => '1',
    'uuid' => '5605c36d-45c1-4968-9009-513f1f084ab1',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Danemark',
    'description' => '',
    'format' => 'html',
    'weight' => '-14',
    'uuid' => '580467d3-e6a8-4052-b07b-ada40777bedc',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Mongolie',
    'description' => '',
    'format' => 'html',
    'weight' => '-6',
    'uuid' => '59134f7e-600b-4783-932c-d12991c96e62',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Tegucigalpa',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '597fdd6a-8472-41e5-a78c-561213b9e59b',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fa91c881-5758-443e-8d6b-0556420244b9',
    ),
  );
  $terms[] = array(
    'name' => 'Alger',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5a846b84-6607-4063-9567-ea0ec94a0252',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ac64aebc-0179-406b-bcc6-0c6484ca1201',
    ),
  );
  $terms[] = array(
    'name' => 'Tibet',
    'description' => NULL,
    'format' => NULL,
    'weight' => '3',
    'uuid' => '5acccd8a-d280-40b1-b1db-c3653402add4',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Mali',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-8',
    'uuid' => '5b0109a6-6c95-4ac5-98b7-5726ce4cf0c4',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Vatican',
    'description' => NULL,
    'format' => NULL,
    'weight' => '28',
    'uuid' => '5b59bbc4-c997-49ba-b0bc-89bbd8c4db45',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'New York',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5c6a4a18-6177-4882-9981-6ec20b196557',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fabd48c5-4b2e-488b-8ae9-c70a320ff0c2',
    ),
  );
  $terms[] = array(
    'name' => 'Pologne',
    'description' => '',
    'format' => 'html',
    'weight' => '-2',
    'uuid' => '5e125aec-bcc1-4c3a-9b36-e795cb512454',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Yougoslavie (ex-)',
    'description' => '',
    'format' => 'html',
    'weight' => '43',
    'uuid' => '6013ef0b-c0c2-48f8-bc32-2fa32a134a17',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Pyongyang',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '628bac1e-6247-4c10-ab40-be57ec98f141',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'c1f9e682-c6ab-42f9-ad3b-b7a70d85e82f',
    ),
  );
  $terms[] = array(
    'name' => 'Italie',
    'description' => '',
    'format' => 'html',
    'weight' => '-5',
    'uuid' => '64eab00c-a563-4cd4-963c-ce4be915f6c9',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Guinée',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-13',
    'uuid' => '6544777c-80be-4e43-862f-68e736350a98',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Helsinki',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '65ff9b4a-df29-4047-923b-e0ff8d9bc400',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'c514f0f2-8506-4a78-99d2-eba98ffb063b',
    ),
  );
  $terms[] = array(
    'name' => 'Togo',
    'description' => NULL,
    'format' => NULL,
    'weight' => '4',
    'uuid' => '67702c43-5aec-485d-8727-865f5d4639a6',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Lucerne',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '69045afe-bdb7-455f-9590-27f132e4f091',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '48b533eb-bc8f-4729-b7ee-26875fa4196c',
    ),
  );
  $terms[] = array(
    'name' => 'Téhéran',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '69fabafd-f496-4dae-8473-87ef80cc901b',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fb59bdac-2d71-4eb2-a135-ae9cfdf918a4',
    ),
  );
  $terms[] = array(
    'name' => 'Cracovie',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6a8606b0-f848-4418-b837-c1d8caf58476',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '5e125aec-bcc1-4c3a-9b36-e795cb512454',
    ),
  );
  $terms[] = array(
    'name' => 'Naples',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6abb1478-369a-41bc-a834-92b20e94a42b',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '64eab00c-a563-4cd4-963c-ce4be915f6c9',
    ),
  );
  $terms[] = array(
    'name' => 'Madagascar',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-9',
    'uuid' => '6acede19-7720-48f4-9148-203890a93f0b',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Liban',
    'description' => '',
    'format' => 'html',
    'weight' => '-7',
    'uuid' => '6ba2f980-fca6-479e-8084-3c92fa5551e8',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Kurdistan',
    'description' => '',
    'format' => 'html',
    'weight' => '-8',
    'uuid' => '6bdee2a7-4439-4a77-8731-26406066609f',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Caracas',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6bf0ccce-be0e-4644-8a1f-438865ef3736',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'd3e34d4a-cacc-4f72-addf-a10942459aa6',
    ),
  );
  $terms[] = array(
    'name' => 'Tchécoslovaquie',
    'description' => '',
    'format' => 'html',
    'weight' => '19',
    'uuid' => '6da9a859-7c58-4cc9-a8dc-79d5dba6577c',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Birmingham',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6fff4719-d92c-4741-9679-f418eb466c6e',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '882938b0-0c38-4e4a-a975-e6270cae9b28',
    ),
  );
  $terms[] = array(
    'name' => 'Bruxelles',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '72a1a131-08d1-4597-a8ef-da74d7c42f65',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '92f5c202-87eb-4af0-9c37-cca07b03b160',
    ),
  );
  $terms[] = array(
    'name' => 'Burundi',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-18',
    'uuid' => '736d8dda-fe90-4387-afd7-1954ebd4a75b',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Pays de Galles',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-2',
    'uuid' => '7401758b-07ec-41f8-b6b4-396932ff1c9e',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Hiroshima',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '741262c7-e3a7-496b-9779-44f84a6c0492',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '217c146b-1efb-4189-a84d-da605e3fc1e3',
    ),
  );
  $terms[] = array(
    'name' => 'Tel-Aviv-Jaffa',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '74a1b02d-dc07-42fe-8e88-fda3c7db983e',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fb1bba97-b299-4a7d-9650-070f22b2e832',
    ),
  );
  $terms[] = array(
    'name' => 'Rome',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '778809d6-52c4-420d-9ee4-06eb114e8ab5',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '64eab00c-a563-4cd4-963c-ce4be915f6c9',
    ),
  );
  $terms[] = array(
    'name' => 'Mauritanie',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-6',
    'uuid' => '78131b14-2e0b-4eed-ae98-ddbb0e6bf695',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'URSS (ex-)',
    'description' => '',
    'format' => 'html',
    'weight' => '21',
    'uuid' => '789bbac5-a9bc-4a17-8397-4b1b3de3087d',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Bruges',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7ad80a36-bc28-4c44-b88a-1ba0226769ab',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '92f5c202-87eb-4af0-9c37-cca07b03b160',
    ),
  );
  $terms[] = array(
    'name' => 'Allemagne',
    'description' => '',
    'format' => 'html',
    'weight' => '-19',
    'uuid' => '7af0a5f7-5388-418f-891b-055e2efcfac5',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Munich',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7bc5b8d8-87f3-4f32-82ab-80d688f67b36',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '7af0a5f7-5388-418f-891b-055e2efcfac5',
    ),
  );
  $terms[] = array(
    'name' => 'Argentine',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '7bfdb7b2-8767-494e-8d33-cfcc501d5ebd',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fc9f4031-1a62-4e3a-9f90-9b2192dd5b21',
    ),
  );
  $terms[] = array(
    'name' => 'Éthiopie',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-15',
    'uuid' => '7ceed8ff-3351-4866-a1d1-c37defe97615',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Écosse',
    'description' => '',
    'format' => 'html',
    'weight' => '-12',
    'uuid' => '7d7bd79f-3ec4-42ed-825c-adb72c6dd584',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Canada',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '7d948fcb-bf1a-455b-aa35-71435dbf1db1',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'f8d32748-3fad-4db6-a3f0-2ba5b9afbd1c',
    ),
  );
  $terms[] = array(
    'name' => 'Bratislava',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7fd6941d-f1f3-4c2b-a40e-5a357a34c234',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '06a26012-163c-4918-b456-df467a314b8c',
    ),
  );
  $terms[] = array(
    'name' => 'Nouvelle-Zélande',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '80c33cbf-9929-4a32-a9cc-72ac0f1a526f',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ca851e3d-ae02-44f0-af36-b95fa0ef0884',
    ),
  );
  $terms[] = array(
    'name' => 'Arménie',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-20',
    'uuid' => '817b930c-3a2e-44f8-9a88-35136a8345f9',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Bolivie',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '840ac2f7-fc9f-4995-8058-607718fd4c57',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fc9f4031-1a62-4e3a-9f90-9b2192dd5b21',
    ),
  );
  $terms[] = array(
    'name' => 'Hanoi',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8489c3d3-7b67-4a5e-a6e0-c8b823510de4',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'd3bcc6ee-f072-4573-b535-0c9e789b5267',
    ),
  );
  $terms[] = array(
    'name' => 'Beijing',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '86f84658-9852-4803-978e-8d7b17da0039',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'bd97a16a-651f-48c1-a91e-753e00127658',
    ),
  );
  $terms[] = array(
    'name' => 'Angleterre',
    'description' => '',
    'format' => 'html',
    'weight' => '-18',
    'uuid' => '882938b0-0c38-4e4a-a975-e6270cae9b28',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Sainte-Lucie',
    'description' => '',
    'format' => 'html',
    'weight' => '3',
    'uuid' => '8a12e23a-6e46-4064-8632-0c537444542c',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'a327d8ca-46ff-4ae5-a913-42777dbc9fcb',
    ),
  );
  $terms[] = array(
    'name' => 'Belgrade',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8a3e5d39-42ec-42ea-bb87-d142ed262a8c',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '1e12936c-ad69-44e8-9e95-34a3e3af02cd',
    ),
  );
  $terms[] = array(
    'name' => 'Genève',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8cbebc89-d8d8-4010-99c6-502ca43010d8',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '48b533eb-bc8f-4729-b7ee-26875fa4196c',
    ),
  );
  $terms[] = array(
    'name' => 'Gabon',
    'description' => '',
    'format' => 'html',
    'weight' => '-15',
    'uuid' => '8de53803-782f-4fa5-a684-351dd98f8951',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Gênes',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8e094166-a565-4abc-96d5-df2dd6cc6c5b',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '64eab00c-a563-4cd4-963c-ce4be915f6c9',
    ),
  );
  $terms[] = array(
    'name' => 'Europe',
    'description' => '',
    'format' => 'html',
    'weight' => '-12',
    'uuid' => '8e561d23-686b-4e28-af92-cff2958089f2',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
  );
  $terms[] = array(
    'name' => 'Bâle',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8e9fdda8-6ecb-4cc0-a138-431fd54ce401',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '48b533eb-bc8f-4729-b7ee-26875fa4196c',
    ),
  );
  $terms[] = array(
    'name' => 'Dublin',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8f60e603-9f36-4dcd-81bf-75ea8c104cf3',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0d56338b-3373-45a4-8267-1eaaa1d809ea',
    ),
  );
  $terms[] = array(
    'name' => 'Sénégal',
    'description' => NULL,
    'format' => NULL,
    'weight' => '2',
    'uuid' => '8fb6b59c-8d3f-48fe-ac99-3a0bf14ae723',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Norvège',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-2',
    'uuid' => '8fdc3b01-6bee-43c8-8d2c-7c647dc4cc05',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Bagdad',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '907c98f0-be17-4b31-9e28-e19a8b2a17e6',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '92d3f907-4b65-4397-9e11-b724d4a13119',
    ),
  );
  $terms[] = array(
    'name' => 'Cuba',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-5',
    'uuid' => '909af47c-fc1a-48d4-8583-afdf06e54368',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'a327d8ca-46ff-4ae5-a913-42777dbc9fcb',
    ),
  );
  $terms[] = array(
    'name' => 'Bangkok',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '929a8e6c-b9a7-4aed-82cb-78c965536ec0',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'cfb59b94-2217-4e71-9399-cd50cf35cbdb',
    ),
  );
  $terms[] = array(
    'name' => 'Irak',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-12',
    'uuid' => '92d3f907-4b65-4397-9e11-b724d4a13119',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Ouganda',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-2',
    'uuid' => '92efa1ca-d015-487a-8eb8-0bb33c0e4fe4',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Belgique',
    'description' => '',
    'format' => 'html',
    'weight' => '-16',
    'uuid' => '92f5c202-87eb-4af0-9c37-cca07b03b160',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Saint-Pétersbourg',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9699acca-f2a6-475f-8a14-04159a0b522c',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fa4372ee-24ec-43a3-8a36-d3e1f36cfc45',
    ),
  );
  $terms[] = array(
    'name' => 'Costa Rica',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-6',
    'uuid' => '9840295b-bbfc-4d11-a8e4-92a6fb11d567',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'a327d8ca-46ff-4ae5-a913-42777dbc9fcb',
    ),
  );
  $terms[] = array(
    'name' => 'Kandahar',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9a5dcd07-0285-4896-b2c9-5b019824ddea',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '09e285ca-8eb2-44e4-a15a-70dd0f5cc6b0',
    ),
  );
  $terms[] = array(
    'name' => 'Melbourne',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9b786cc1-5502-4f06-b9f3-4f48e9a1666a',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'e7c3f64c-ad61-4b3d-b0a1-50caee66a86b',
    ),
  );
  $terms[] = array(
    'name' => 'Montego Bay',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9dfdc6d1-8140-44a9-8563-3f99ac7d8d63',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ae29a736-9d32-425c-b2ab-7bf3984365ab',
    ),
  );
  $terms[] = array(
    'name' => 'Managua',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9e16f225-d905-44fc-a51b-8ca4c29916a7',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'd48d21eb-525a-424c-a233-785baa4294a4',
    ),
  );
  $terms[] = array(
    'name' => 'Aberdeen',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9e5164fa-4c5a-4d2a-95df-f342be62d2eb',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '7d7bd79f-3ec4-42ed-825c-adb72c6dd584',
    ),
  );
  $terms[] = array(
    'name' => 'Budapest',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9f041975-589e-44c4-b049-99519f0d4542',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '09562c69-1fcb-4902-a3e9-2121ff8d985f',
    ),
  );
  $terms[] = array(
    'name' => 'Manchester',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9f414238-8ebb-4459-b324-c72a759a9cae',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '882938b0-0c38-4e4a-a975-e6270cae9b28',
    ),
  );
  $terms[] = array(
    'name' => 'Turquie',
    'description' => '',
    'format' => 'html',
    'weight' => '10',
    'uuid' => '9f61a152-c3fd-42f9-b0d9-f46af39a94fc',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Kingston',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a08e8d6a-822f-4085-83e1-dfd3f5ad4f1c',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ae29a736-9d32-425c-b2ab-7bf3984365ab',
    ),
  );
  $terms[] = array(
    'name' => 'Égypte',
    'description' => '',
    'format' => 'html',
    'weight' => '-15',
    'uuid' => 'a10d4f45-8401-4d71-9ae8-19875f329575',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Corée du Sud',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-16',
    'uuid' => 'a296a9ab-792c-429c-9004-7714690a8d88',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Amérique centrale',
    'description' => '',
    'format' => 'html',
    'weight' => '-13',
    'uuid' => 'a327d8ca-46ff-4ae5-a913-42777dbc9fcb',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
  );
  $terms[] = array(
    'name' => 'Cameroun',
    'description' => '',
    'format' => 'html',
    'weight' => '-17',
    'uuid' => 'a68c14e2-fab4-4165-910e-c73b52e432b4',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Espagne',
    'description' => '',
    'format' => 'html',
    'weight' => '-11',
    'uuid' => 'a7ede740-480c-49db-9297-82cc51c0e322',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'République tchèque',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a859c3a4-89cf-4e0d-b6ab-700fe80f33e7',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Tchad',
    'description' => NULL,
    'format' => NULL,
    'weight' => '3',
    'uuid' => 'a9d9a8ba-341a-46b2-b76d-ea13a86d1ad3',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Croatie',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-8',
    'uuid' => 'a9fbc80a-b60b-4015-b025-38a46639331d',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Lausanne',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ab122b6f-f4b9-4dd5-980a-37998bcc0cdd',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '48b533eb-bc8f-4729-b7ee-26875fa4196c',
    ),
  );
  $terms[] = array(
    'name' => 'Copenhague',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ab7c09c9-ed94-463e-9f42-1c0148d15837',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '580467d3-e6a8-4052-b07b-ada40777bedc',
    ),
  );
  $terms[] = array(
    'name' => 'Algérie',
    'description' => '',
    'format' => 'html',
    'weight' => '-25',
    'uuid' => 'ac64aebc-0179-406b-bcc6-0c6484ca1201',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Varsovie',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ac887183-d43a-423e-88ba-44c14bd62f6e',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '5e125aec-bcc1-4c3a-9b36-e795cb512454',
    ),
  );
  $terms[] = array(
    'name' => 'San Francisco',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'acf6239b-b61f-42b9-965b-552166bdbfd4',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fabd48c5-4b2e-488b-8ae9-c70a320ff0c2',
    ),
  );
  $terms[] = array(
    'name' => 'Botswana',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-21',
    'uuid' => 'ad67e215-eb8c-4a94-bd42-5aa54749d767',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Rwanda',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-1',
    'uuid' => 'add21d1a-6a38-406a-8e0c-ad9230736fba',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Jamaïque',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ae29a736-9d32-425c-b2ab-7bf3984365ab',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'a327d8ca-46ff-4ae5-a913-42777dbc9fcb',
    ),
  );
  $terms[] = array(
    'name' => 'Zurich',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'af54d419-3bf9-4d9e-91e9-52186097417f',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '48b533eb-bc8f-4729-b7ee-26875fa4196c',
    ),
  );
  $terms[] = array(
    'name' => 'Lima',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b0ad7e5e-b3c8-440b-85c4-0e8dfd9e0bfd',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '1e31833b-f6a0-4e97-af67-289ee82c58d6',
    ),
  );
  $terms[] = array(
    'name' => 'Düsseldorf',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b175ffab-2fef-4939-b17c-638565c589a8',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '7af0a5f7-5388-418f-891b-055e2efcfac5',
    ),
  );
  $terms[] = array(
    'name' => 'Ukraine',
    'description' => '',
    'format' => 'html',
    'weight' => '20',
    'uuid' => 'b19fc95f-5d3c-40a2-acfa-200ebea16b5f',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Brasilia',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b21f0179-f6a4-4fe5-9d95-307e08419c0d',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '3fdd3534-6d74-4c02-aa9b-45e02503c77d',
    ),
  );
  $terms[] = array(
    'name' => 'Côte d\'Ivoire',
    'description' => '',
    'format' => 'html',
    'weight' => '-15',
    'uuid' => 'b3789739-c907-40a0-8092-d52644b499ed',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Sydney',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b6754b6d-484b-41ca-9eae-2a4e95c4cf60',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'e7c3f64c-ad61-4b3d-b0a1-50caee66a86b',
    ),
  );
  $terms[] = array(
    'name' => 'Taïwan',
    'description' => NULL,
    'format' => NULL,
    'weight' => '1',
    'uuid' => 'b6eb04d5-3dd8-400d-896a-7a726d728c71',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Berne',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b782d244-5adb-4bde-a610-938c7d90d413',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '48b533eb-bc8f-4729-b7ee-26875fa4196c',
    ),
  );
  $terms[] = array(
    'name' => 'Cali',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b816e76a-6b5b-468f-9397-d5340b1d5d31',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '2bc97af0-f9a6-43c9-aa49-c1b606abcb9f',
    ),
  );
  $terms[] = array(
    'name' => 'Belfast',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b829c72b-abb7-4cf7-b9f0-58a730fc5588',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0d56338b-3373-45a4-8267-1eaaa1d809ea',
    ),
  );
  $terms[] = array(
    'name' => 'Salvador',
    'description' => '',
    'format' => 'html',
    'weight' => '4',
    'uuid' => 'bc06200d-3ecc-48d4-bda1-81c51b75da40',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'a327d8ca-46ff-4ae5-a913-42777dbc9fcb',
    ),
  );
  $terms[] = array(
    'name' => 'Porto',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'bc4095dc-9065-4002-ba0a-5247c6c62011',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '110f9619-f29f-4321-98cd-789419c3026a',
    ),
  );
  $terms[] = array(
    'name' => 'Chine',
    'description' => '',
    'format' => 'html',
    'weight' => '-18',
    'uuid' => 'bd97a16a-651f-48c1-a91e-753e00127658',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Barcelone',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'be3b3a45-f31b-4337-bb9d-e7f3b7f4e528',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'a7ede740-480c-49db-9297-82cc51c0e322',
    ),
  );
  $terms[] = array(
    'name' => 'Christchurch',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'bee8394a-c3ab-44eb-a387-84d84cf67739',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '80c33cbf-9929-4a32-a9cc-72ac0f1a526f',
    ),
  );
  $terms[] = array(
    'name' => 'Édimbourg',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c16dcf96-cc35-4d49-84f1-453bab014855',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '7d7bd79f-3ec4-42ed-825c-adb72c6dd584',
    ),
  );
  $terms[] = array(
    'name' => 'Corée du Nord',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-17',
    'uuid' => 'c1f9e682-c6ab-42f9-ad3b-b7a70d85e82f',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Cambodge',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-19',
    'uuid' => 'c21b20cf-2aae-4c86-9454-b225329438ef',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Kenya',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-12',
    'uuid' => 'c3600ac9-9f8e-4f23-8073-3b20349f7f95',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Wellington',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c4576e5d-e2e9-4a39-a51b-a2b929ec6815',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '80c33cbf-9929-4a32-a9cc-72ac0f1a526f',
    ),
  );
  $terms[] = array(
    'name' => 'Finlande',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-8',
    'uuid' => 'c514f0f2-8506-4a78-99d2-eba98ffb063b',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Singapour',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c5c0c93d-9c3b-4814-b421-4a6654599f40',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Roumanie',
    'description' => NULL,
    'format' => NULL,
    'weight' => '4',
    'uuid' => 'c81a06f0-9c7a-4f6d-91b2-ad935a9a4e66',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Mexique',
    'description' => '',
    'format' => 'html',
    'weight' => '2',
    'uuid' => 'c889463d-64b5-4942-93f1-e8e39a315354',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'f8d32748-3fad-4db6-a3f0-2ba5b9afbd1c',
    ),
  );
  $terms[] = array(
    'name' => 'Chili',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c8e776ef-3552-4b3e-a24e-636c9959f6c1',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fc9f4031-1a62-4e3a-9f90-9b2192dd5b21',
    ),
  );
  $terms[] = array(
    'name' => 'Burkina Faso',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-19',
    'uuid' => 'ca1672d7-600f-42a8-a8dc-88b66d655fda',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Océanie',
    'description' => '',
    'format' => 'html',
    'weight' => '-12',
    'uuid' => 'ca851e3d-ae02-44f0-af36-b95fa0ef0884',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
  );
  $terms[] = array(
    'name' => 'Palestine',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-1',
    'uuid' => 'caf28c1c-6d28-4938-9bc4-a4cff1ec5c82',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Odessa',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'cc2495fa-991e-4ca3-b4db-a040d5fc37aa',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'b19fc95f-5d3c-40a2-acfa-200ebea16b5f',
    ),
  );
  $terms[] = array(
    'name' => 'Islamabad',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'cdde519f-1eea-44b7-8c8d-2f46685a369d',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fe0aec8b-d1f4-4d84-8b52-d61ad9ab5e79',
    ),
  );
  $terms[] = array(
    'name' => 'Antilles',
    'description' => '',
    'format' => 'html',
    'weight' => '-7',
    'uuid' => 'cee0b981-d05a-4389-8d71-d9353c438547',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'a327d8ca-46ff-4ae5-a913-42777dbc9fcb',
    ),
  );
  $terms[] = array(
    'name' => 'Kyoto',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'cef4f172-5147-43ef-9b8f-647153f3c0a9',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '217c146b-1efb-4189-a84d-da605e3fc1e3',
    ),
  );
  $terms[] = array(
    'name' => 'Thaïlande',
    'description' => NULL,
    'format' => NULL,
    'weight' => '2',
    'uuid' => 'cfb59b94-2217-4e71-9399-cd50cf35cbdb',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Turin',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'cfe1e0ab-ee4e-4325-b671-b7eacbd2ec7f',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '64eab00c-a563-4cd4-963c-ce4be915f6c9',
    ),
  );
  $terms[] = array(
    'name' => 'Milan',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd0053a0c-051c-4259-90b5-ef26469b3707',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '64eab00c-a563-4cd4-963c-ce4be915f6c9',
    ),
  );
  $terms[] = array(
    'name' => 'Afrique du Sud',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-26',
    'uuid' => 'd1acc691-f78a-4988-8534-21f1563df3a5',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Somalie',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd1d0a8a5-08b7-48f6-bdab-2a0bc9c712f7',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Sao Paulo',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd270e32a-dcc1-40a0-876b-01ada17da751',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '3fdd3534-6d74-4c02-aa9b-45e02503c77d',
    ),
  );
  $terms[] = array(
    'name' => 'Viêt Nam',
    'description' => NULL,
    'format' => NULL,
    'weight' => '37',
    'uuid' => 'd3bcc6ee-f072-4573-b535-0c9e789b5267',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Venezuela',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd3e34d4a-cacc-4f72-addf-a10942459aa6',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fc9f4031-1a62-4e3a-9f90-9b2192dd5b21',
    ),
  );
  $terms[] = array(
    'name' => 'Nicaragua',
    'description' => NULL,
    'format' => NULL,
    'weight' => '3',
    'uuid' => 'd48d21eb-525a-424c-a233-785baa4294a4',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'a327d8ca-46ff-4ae5-a913-42777dbc9fcb',
    ),
  );
  $terms[] = array(
    'name' => 'Bristol',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd6ccd3a9-136a-4655-802e-c7a898c7dfad',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '882938b0-0c38-4e4a-a975-e6270cae9b28',
    ),
  );
  $terms[] = array(
    'name' => 'Ankara',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd7a20806-1b5b-455d-9eab-2a8df614b80c',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '9f61a152-c3fd-42f9-b0d9-f46af39a94fc',
    ),
  );
  $terms[] = array(
    'name' => 'Cardiff',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd8139e29-f58d-4208-a032-69c438599bc1',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '7401758b-07ec-41f8-b6b4-396932ff1c9e',
    ),
  );
  $terms[] = array(
    'name' => 'Lisbonne',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'dd1c423f-98f1-467d-9903-383301925cc7',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '110f9619-f29f-4321-98cd-789419c3026a',
    ),
  );
  $terms[] = array(
    'name' => 'Liège',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'df40e569-8df4-482b-a1e4-58089976056e',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '92f5c202-87eb-4af0-9c37-cca07b03b160',
    ),
  );
  $terms[] = array(
    'name' => 'Kaboul',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'dfc9304f-69f5-4ba3-8ee0-f555f0128508',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '09e285ca-8eb2-44e4-a15a-70dd0f5cc6b0',
    ),
  );
  $terms[] = array(
    'name' => 'Ljubljana',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e02d81ad-416a-4a46-8973-d24111e5fdd7',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '23d61b6b-ece1-4c27-ae4f-40b2c189aaee',
    ),
  );
  $terms[] = array(
    'name' => 'France',
    'description' => '',
    'format' => 'html',
    'weight' => '-8',
    'uuid' => 'e2372206-b612-48c4-ad72-7ac1703af9da',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Leeds',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e2500eb9-2f6e-499b-bfd8-e039a48d1c36',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '882938b0-0c38-4e4a-a975-e6270cae9b28',
    ),
  );
  $terms[] = array(
    'name' => 'Kharkiv',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e3ad4e56-59b2-44fa-8799-3c64fefd58e6',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'b19fc95f-5d3c-40a2-acfa-200ebea16b5f',
    ),
  );
  $terms[] = array(
    'name' => 'Lahore',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e4000b54-1185-4f84-bfff-441d46679e76',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fe0aec8b-d1f4-4d84-8b52-d61ad9ab5e79',
    ),
  );
  $terms[] = array(
    'name' => 'Suède',
    'description' => '',
    'format' => 'html',
    'weight' => '16',
    'uuid' => 'e56c38b9-a86f-4e5d-a28b-3963ef312000',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Amsterdam',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e660a108-ac09-487f-bb6e-1fe6afab9c77',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0872d081-dcd4-4cf6-99ee-a4862511f68e',
    ),
  );
  $terms[] = array(
    'name' => 'Boston',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e6639489-2de4-4843-bc2b-ee2679d40023',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fabd48c5-4b2e-488b-8ae9-c70a320ff0c2',
    ),
  );
  $terms[] = array(
    'name' => 'Alaska',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e72db327-4d93-4139-809d-457bcbba77e1',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fabd48c5-4b2e-488b-8ae9-c70a320ff0c2',
    ),
  );
  $terms[] = array(
    'name' => 'Australie',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e7c3f64c-ad61-4b3d-b0a1-50caee66a86b',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ca851e3d-ae02-44f0-af36-b95fa0ef0884',
    ),
  );
  $terms[] = array(
    'name' => 'Congo',
    'description' => '',
    'format' => 'html',
    'weight' => '-16',
    'uuid' => 'e7ee0676-dd6f-4936-9a43-bc03c1f89db6',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Athènes',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e82b3c07-afa2-4fac-971e-367b107eeb9b',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'eb52bcdc-09ec-4b7c-8659-0524d1b4d91d',
    ),
  );
  $terms[] = array(
    'name' => 'Martinique',
    'description' => '',
    'format' => 'html',
    'weight' => '1',
    'uuid' => 'e84c1058-25b5-4d2e-a314-46daabb93969',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'a327d8ca-46ff-4ae5-a913-42777dbc9fcb',
    ),
  );
  $terms[] = array(
    'name' => 'Port Moresby',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e9571078-20c0-47ca-8979-028778cac919',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '45a4980a-5b5b-4a83-af29-9c974c9dea28',
    ),
  );
  $terms[] = array(
    'name' => 'Grèce',
    'description' => '',
    'format' => 'html',
    'weight' => '-8',
    'uuid' => 'eb52bcdc-09ec-4b7c-8659-0524d1b4d91d',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Port-au-Prince',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ec33e71b-242f-4155-b9b5-2838f13734f9',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '03bb0fa2-eb93-4d08-b6f2-5df72adf4857',
    ),
  );
  $terms[] = array(
    'name' => 'Malaisie',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ed3e336a-6a5a-4d69-bc63-c91d81332426',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Bélize',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-7',
    'uuid' => 'ee58e1ae-3829-4e0e-b1fd-c1e903fe9348',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'a327d8ca-46ff-4ae5-a913-42777dbc9fcb',
    ),
  );
  $terms[] = array(
    'name' => 'Tirana',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'eeb905f2-5961-4070-bcb8-37cc9ccf4d0a',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '432c09d3-6bee-448f-ad43-485548d2a6ba',
    ),
  );
  $terms[] = array(
    'name' => 'Maroc',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-7',
    'uuid' => 'ef8aed17-24b4-4a51-acad-b8da56ffb209',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Anvers',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f15c8994-d17c-4a59-bffc-2701618a087f',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '92f5c202-87eb-4af0-9c37-cca07b03b160',
    ),
  );
  $terms[] = array(
    'name' => 'Ghana',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-14',
    'uuid' => 'f1cf43a8-45d5-47a2-9fd5-b04a26b6a6e4',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '0310432d-ce25-4c6b-b5d2-3ea8ea0d24c2',
    ),
  );
  $terms[] = array(
    'name' => 'Bucarest',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f29cd01f-acc8-4fef-b563-cd8a48fb8323',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'c81a06f0-9c7a-4f6d-91b2-ad935a9a4e66',
    ),
  );
  $terms[] = array(
    'name' => 'Toronto',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f44dda47-7b72-4986-8bb0-f5eb98f0bc16',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '7d948fcb-bf1a-455b-aa35-71435dbf1db1',
    ),
  );
  $terms[] = array(
    'name' => 'Istanbul',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f5123795-e1f0-4dcf-8c95-1e2e1950e073',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '9f61a152-c3fd-42f9-b0d9-f46af39a94fc',
    ),
  );
  $terms[] = array(
    'name' => 'Washington',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f72b3edb-734e-441e-9866-2895e3cfcbfe',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fabd48c5-4b2e-488b-8ae9-c70a320ff0c2',
    ),
  );
  $terms[] = array(
    'name' => 'Moscou',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f7b1b6b0-4a3a-48b1-b503-aa1636c5e535',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'fa4372ee-24ec-43a3-8a36-d3e1f36cfc45',
    ),
  );
  $terms[] = array(
    'name' => 'Guatemala',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-3',
    'uuid' => 'f7dc3263-2adc-45f0-a371-e7f81f8f6834',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'a327d8ca-46ff-4ae5-a913-42777dbc9fcb',
    ),
  );
  $terms[] = array(
    'name' => 'Amérique du nord',
    'description' => '',
    'format' => 'html',
    'weight' => '-12',
    'uuid' => 'f8d32748-3fad-4db6-a3f0-2ba5b9afbd1c',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
  );
  $terms[] = array(
    'name' => 'Madrid',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f96315d4-845f-440c-83aa-161eb7f662e0',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'a7ede740-480c-49db-9297-82cc51c0e322',
    ),
  );
  $terms[] = array(
    'name' => 'Russie',
    'description' => '',
    'format' => 'html',
    'weight' => '6',
    'uuid' => 'fa4372ee-24ec-43a3-8a36-d3e1f36cfc45',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '8e561d23-686b-4e28-af92-cff2958089f2',
    ),
  );
  $terms[] = array(
    'name' => 'Honduras',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-1',
    'uuid' => 'fa91c881-5758-443e-8d6b-0556420244b9',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'a327d8ca-46ff-4ae5-a913-42777dbc9fcb',
    ),
  );
  $terms[] = array(
    'name' => 'Inverness',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'fa934c5b-b49f-43d1-a865-3fcad859da09',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '7d7bd79f-3ec4-42ed-825c-adb72c6dd584',
    ),
  );
  $terms[] = array(
    'name' => 'États-Unis',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'fabd48c5-4b2e-488b-8ae9-c70a320ff0c2',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'f8d32748-3fad-4db6-a3f0-2ba5b9afbd1c',
    ),
  );
  $terms[] = array(
    'name' => 'Israël',
    'description' => '',
    'format' => 'html',
    'weight' => '-15',
    'uuid' => 'fb1bba97-b299-4a7d-9650-070f22b2e832',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Iran',
    'description' => '',
    'format' => 'html',
    'weight' => '-11',
    'uuid' => 'fb59bdac-2d71-4eb2-a135-ae9cfdf918a4',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Amérique du sud',
    'description' => '',
    'format' => 'html',
    'weight' => '-12',
    'uuid' => 'fc9f4031-1a62-4e3a-9f90-9b2192dd5b21',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
  );
  $terms[] = array(
    'name' => 'Auckland',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'fd1a33ef-1a30-4675-ad45-0c4abf2a45c8',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => '80c33cbf-9929-4a32-a9cc-72ac0f1a526f',
    ),
  );
  $terms[] = array(
    'name' => 'Maracaibo',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'fdb1ddbd-97d2-4b5b-bc73-3ea274b60bb9',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'd3e34d4a-cacc-4f72-addf-a10942459aa6',
    ),
  );
  $terms[] = array(
    'name' => 'Pakistan',
    'description' => NULL,
    'format' => NULL,
    'weight' => '-2',
    'uuid' => 'fe0aec8b-d1f4-4d84-8b52-d61ad9ab5e79',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    ),
  );
  $terms[] = array(
    'name' => 'Paris',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'feb0c5a8-5dba-4d40-a1fa-7e4ae5b61392',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'e2372206-b612-48c4-ad72-7ac1703af9da',
    ),
  );
  $terms[] = array(
    'name' => 'Asie',
    'description' => '',
    'format' => 'html',
    'weight' => '-12',
    'uuid' => 'ff364b61-da3c-4c9d-af3c-f409a333ac53',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
  );
  $terms[] = array(
    'name' => 'Kuala Lumpur',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ff714b6a-0dcf-4ae4-a6f0-aecf1a2e6da6',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'provenance',
    'parent' => array(
      0 => 'ed3e336a-6a5a-4d69-bc63-c91d81332426',
    ),
  );
  return $terms;
}
