<?php
/**
 * @file
 * oic_taxonomie_courants_artistiques.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function oic_taxonomie_courants_artistiques_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'anarchisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '05bbc480-c91e-43a4-832c-10c0eda9f45b',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'néo-hipsterisme',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '07da9cb8-613c-4bf1-a3eb-210f834f86b4',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'expressionnisme abstrait',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0d336f61-fa4d-439e-a7f5-f351a5322d5c',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'action painting',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1036b97c-494c-42c2-850f-a0bb6f966407',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'art brut',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1078eeb2-f1b2-4d16-9b82-4f845d10f5b7',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'humanisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '133ff3c8-8afe-4d3c-b127-ce181749e95a',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'néo-dada',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '14c01321-f1ac-4f37-a248-c5932fdefbda',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'Londres (École de)',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '162424c4-1495-44b9-9c69-ae23e014a97f',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'body art',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '165066ca-358c-47d5-a19a-5a969caa4572',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'néo-pop',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1787c9db-0a24-40df-ab5c-917215ca6456',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'minimalisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '18200fee-99e1-42e8-a70d-aefa446251b8',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'nouveau romantisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '187f03b6-bd5a-4e56-a0a9-7106892c05e4',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'De Stijl',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '19a46d86-5c3f-43be-a52e-66feb6b77e07',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'Cobra',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1a281101-15d0-4370-a823-218e7e153d0c',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'rococo',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1a635976-2a1f-4bb7-9ade-97d13b1c3ddc',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'Francfort (École de)',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1c987cb0-b1cf-48e4-bc9c-9a1f016810dd',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'réalisme bourgeois',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '241da44f-e125-4c20-8ce8-71c393237f54',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'structuralisme',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '246f7482-33e7-478e-b7dd-9c7fac3a9383',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'surréalisme',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '27404946-4532-4671-a3d4-b640e7f0deee',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'art concret',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '28fff72e-e572-4ca5-8908-2b3992e5e84f',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'fauvisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2d8da86b-10ea-44a3-b058-80eef28cf28d',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'flux de conscience',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2e8f07f3-876e-4e13-a3cd-5da0530ee334',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'art cinétique',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '33d78b83-38ba-4267-8d51-0bf632eb0338',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'new criticism',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '35f654a3-51b7-4d0e-952e-d22ad6538ec5',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'concrétisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '360c4626-a8e1-4b46-9126-0b436156da7b',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'impressionnisme',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '377eb71d-7901-4599-8e15-789de96e60d8',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'cinéma-vérité',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3854f695-9cd4-4f72-9425-b76fa85c797d',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'orphisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '38e1d22e-ca8c-4b3e-889a-f9bb371f894e',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'art abstrait',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3b2f364b-d320-4a7f-9d78-dcde2762fb85',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'art déco',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3bb213d8-9148-424a-8027-0ac51d3331ee',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'absurde (théâtre de l\')',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '3c7c05bf-086d-4079-8f44-a7c292837313',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'hyperréalisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4174cb69-3c1d-414d-a52a-4ea52c1659f5',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'constructivisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '41b09ed1-abf9-4a1a-a3aa-4bf547679cec',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'primitivisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4255c10a-c890-44f5-a444-1be87e2eef0c',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'déprimisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '44009866-7c7e-4754-9ca2-8cd1282b3e13',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'néohumanisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '46a3c19e-7435-4f14-8bfe-8c8ab2e990da',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'hipsterisme',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '4727aa5c-5003-46f1-b180-57c1e16a11e1',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'art conceptuel',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '473c5335-5b6a-4040-8e76-0a742428a28d',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'néo-expressionnisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '49c4613a-7a87-430f-aec8-af2244f65804',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'art naïf',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4a32e4a1-4bef-4527-b5c9-6e9616827024',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'post-exotisme',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '4cba0d2b-98b1-4b1d-a4a3-0a12c8092b45',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'synthétisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '51538368-99a4-4e8c-8e11-e54e38deac59',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'néo-gothique',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '54925e58-de82-411d-82d8-18bd8d639825',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'divisionnisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5513b901-6cc5-4422-8a97-acb24c4ffe8f',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'vorticisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '562c70c4-ec81-4be3-9837-fc02917de5e8',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'avant-gardisme',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '5bcb19a4-3396-4b96-aebe-ba35ba83f679',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'néosurréalisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5d0900d0-c2a7-4a57-9852-00881cf6763a',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'rayonnisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5e562a5d-a877-42dc-a653-bbb435d38e39',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'contemporain',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5f4df12b-568a-442e-8084-75160584e4c1',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'street art',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '63207401-275a-469f-9ccb-abd96c158af8',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'naturalisme',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '637ca275-cef8-462b-875b-a182c2fc9f85',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'Beat Generation',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '65451329-a3a1-4339-a49c-0eb25504453c',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'renaissance',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '69652819-4cfc-4759-8afb-2165b942ae1a',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'néoprimitivisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6b1e9ec3-b477-4fb9-8138-d8d49f2fe991',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'photoréalisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6eb80c27-e3ee-4906-ac8f-f3b359fad7fd',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'Sturm und Drang',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '73c1f217-98c7-4362-895d-a2c9a2fe2fc9',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'dadaïsme',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '75f85298-9ed6-4275-94f5-407798347303',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'modernisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7ac67826-cc3e-4d01-a6a0-6666459a26c7',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'réalisme fantastique',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7c6fe29e-1415-49fa-ac7c-bcae7a5f0898',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'lettrisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7d9f5010-c85d-4b08-9bb7-6a550467662e',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'massuréalisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7e6b9757-91d4-4a6a-a461-9a7d652e7f55',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'positivisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7ed0534b-5071-424d-a667-07cfb0f0801d',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'moralisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7f23902a-4ea7-4070-a2d9-c318a1c9ab4b',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'symbolisme',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '858d1d9c-b8dc-4303-94d3-572fc0d18119',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'pataphysique',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '88299cf0-1ddf-4677-87b9-2c6e36a4ee7a',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'classicisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8981f4dd-1caf-40c2-b43e-ac223c7af11f',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'op art',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8a0733da-d70a-4b79-afcc-95ebd010449a',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'burlesque',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8a808320-acf7-45c4-b192-b18c3da49a8e',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'les Lumières',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8be3a829-404c-4b55-ab33-d9b912e32bae',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'scientisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8e9c59d7-70f0-4e55-a1c9-4547bd49329b',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'objectivisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8ebd83d2-2e05-4c37-be1f-fb223a4458cc',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'postmodernisme',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '91097706-18c0-4919-b03e-af76a82c172f',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'art vidéo',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '91a8356c-5738-4a4f-85a3-eb0f51ee2956',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'futurisme',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '92fb8c30-6a43-40f8-a8c2-4de3a27c06ec',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'behavorisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9996fe74-25f5-4c01-b289-393589a229fc',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'tachisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9ab2262e-b024-4ba2-b06a-824fe81bd94e',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'automatisme',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '9fa4c9a2-6e9f-4d30-a7d9-7593cdd8790e',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'populisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a31d6700-7ce7-4181-ad3b-016373f837e8',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'africanisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a3f56d11-9d3c-46bc-b49c-17ee65ab0547',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'sécessionnisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a57f8d98-6578-42cc-9173-df926ecb73bc',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'négritude',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a5bd5ab7-fc8b-44f2-8585-2443f7338d1a',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'expressionnisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a5c2ff96-c656-4f7d-892a-8f18996389f8',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'nouveau théâtre',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a67445d9-8f59-4186-8a6b-83761ded64e0',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'postimpressionnisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'aac6fdd3-f6a0-437a-867b-00e5cc9bf25e',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'extrême contemporain',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ab23e597-9f02-45fc-9ace-42157e053232',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'néoromantisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ac9822c3-a381-48c6-a56d-8b83457cb33f',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'art corporel',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ad0c8f4d-7ccc-4053-ae9f-ab61557b2b7d',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'gothique',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b335c7b5-534e-4e56-8e3a-4a9aeecd4fed',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'subjectivisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'bb54d4ba-676b-484f-9347-f07439c7ea96',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'réalisme magique',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'bf2ed061-aca5-4517-9eec-21efb50870c7',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'créationnisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c586c3b4-e22c-4647-9e6d-199b15bcc4a0',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'Génération perdue',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'c5cbe270-367f-4344-845c-d625530a14c9',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'Nouveau Roman',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'c6b4e0d7-17b5-49ff-8932-e331739f8d7f',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'cubisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c6ca9e77-eb5b-4e9e-954c-f28ec89ebd53',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'internationalisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ca5edb4e-9b89-483e-834c-2822d8d3e861',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'arte povera',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'cacdb1ea-5de8-4f70-a25c-930c84815518',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'néoplasticisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'cf1329ab-bdb1-4a4e-9981-07aede306b54',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'néoclassicisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd00c1aa4-ae99-4fa4-b906-c77867d8309f',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'Bauhaus',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'd16e99d0-388c-4da4-a7ec-24f81dee300c',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'Nouvelle Vague',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'd2c90c09-99a4-4b76-b860-2d4b29398a7f',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'situationnisme',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'd58b739f-882f-4212-bbbd-bbeb1f9021f0',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'Nouvelle Objectivité',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd9f78e36-4974-4259-a9d9-7335e5d3cb52',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'réalisme poétique',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'da061497-49fa-4b5f-9c66-bbba2eef31f6',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'baroque',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'da29dad1-7ad0-4d40-a6e0-81796296aac7',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'nouveau réalisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'db75c32a-4c87-4fcd-9c72-e351f200fbcd',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'unanimisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'dfbd89c8-25a9-4c40-9a8a-1074fc0a5ea9',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'pop art',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'e1152eb4-ff25-4d03-86a2-a509da250b08',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'décadentisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e11ad8cb-758c-45e2-8463-32769d3c6902',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'maniérisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e34419b2-1b71-44f9-b1b9-a93c586bfc65',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'romantisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e425271b-1f67-4fb0-8a0d-abb58b997179',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'réalisme socialiste',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e4822b7c-2a61-4ff1-8332-2c6fd23ad966',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'Oulipo',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e9b8525e-3f5d-46be-a2e6-5f17fd95e583',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'précisionnisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ee17edb1-6b74-42ca-82a0-15874aa472ed',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'néo-impressionnisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ee89b03d-57ef-40e6-8526-bec9e1fb445c',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'fluxus',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ef477a04-12ea-48c6-95e3-ffb7dfc7292e',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'réalisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f139c64d-f7c0-42f1-9bcf-838918a853d0',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'cinema novo',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f17d4bf7-16f7-47e0-9b29-9984895a7eef',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'formalisme',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'f2d0c15d-886e-4d71-9d06-2528deb20b52',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'néo-avant-garde',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'f4739c76-9796-4e1f-951e-96201fc48587',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'déconstructivisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f6368d86-cf0d-4235-b3b8-890cca11d096',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'muralisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f646b8a5-3186-4db5-a027-b873974797d0',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'réalisme social',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f9b9f202-8ae4-404d-b0af-65967fe5c7a5',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'existentialisme',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'fdad88f9-c895-4633-8c2f-6dd507f4524f',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'poésie concrète',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'fe914e6c-842f-408a-b4a5-9b609a08e041',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  $terms[] = array(
    'name' => 'art nouveau',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ff9dd888-723e-47a8-95ff-5c732a0001d7',
    'language' => 'und',
    'i18n_tsid' => '0',
    'vocabulary_machine_name' => 'contenu',
  );
  return $terms;
}
