<?php
// $Id: cincopa.module,v 1.1 2010/10/04 22:28:02 asak Exp $

/**
 * @file
 * Include Cincopa Multimedia Platform (http://www.cincopa.com/) in Drupal
 */

/**
 * Implements hook_page_alter().
 */
function cincopa_page_alter(&$page) {
  if (user_access('View the administration theme') && path_is_admin(current_path())) {
    drupal_add_css(drupal_get_path('module', 'cincopa') . '/cincopa.css');
    drupal_add_js(drupal_get_path('module', 'cincopa') . '/plugin/plugin.js');
    
    $output = '';
    if(!isset($_COOKIE['cincopa_help_close'])) {
      $output = '<div class="cincopa_help_wrapper"><div id="icon_close" class="icon-close"></div><div class="cincopa_help"><p>
        <img src="https://www.cincopa.com/_cms/design15/icons/favicon-32.png?affdata=drupal-plugin-7,welcome-msg" height="15px">
        Welcome to Cincopa Rich Media Plugin - the most popular way to add videos, photo galleries, slideshows, Cooliris gallery, podcast and music to your site.</p>Check our
      <input type="button" class="form-submit" value="Welcome page" onclick="window.open(\'https://www.cincopa.com/drupal/welcome\');"> for registration and support documents.</div></div><br/>';
      if (isset($page['help'])) {
        $output .= $page['help']['system_help']['#markup'];
      }
    }
    $page['help']['system_help']['#markup'] = $output;
  }
}

/**
 * Implements hook_wysiwyg_plugin().
 */
function cincopa_wysiwyg_plugin($editor, $version) {
  drupal_add_css(drupal_get_path('module', 'cincopa') . '/cincopa.css');
  switch ($editor) {
    case 'ckeditor':
      return array(
        'cincopa' => array(
          'path' => drupal_get_path('module', 'cincopa') . '/plugin',
          'url' => '',
          'filename' => 'plugin.js',
          'buttons' => array(
            'cincopa_new_gallery' => t('Cincopa New Gallery'),
            'cincopa_items' => t('Cincopa'),
          ),
          'load' => TRUE,
          'internal' => FALSE,
        ),
      );
      break;
  }
}

/**
 * Implements hook_filter_info().
 */
function cincopa_filter_info() {
    $filters['filter_cincopa'] = array(
        'title' =>  t('Parse Cincopa Tags'),
        'description' => t('Parse the Cincopa tag and replace it with the gallery code.'),
        'cache' => FALSE,
        'process callback' => '_filter_cincopa',
        'tips callback' => '_filter_cincopa_tips',
    );
    return $filters;
}

/**
 * Processes the cincopa filter
 */
function _filter_cincopa($text, $filter, $format, $langcode, $cache, $cache_id) {
    $text = preg_replace_callback('/\[cincopa ([[:print:]]+?)\]/', 'cincopa_plugin_callback', $text);
    return $text;
}

/**
 * Returns the filter information for the filter help page
 */
function _filter_cincopa_tips($filter, $format, $long = FALSE) {
    if ($long) {
        return t('Insert a Cincopa gallery (Use the syntax "@example").', array('@example' => '[cincopa 10465673]'));
    }
    else {
        return t('Insert a Cincopa gallery using the tag "@example" (without the quotes). Replace the numbers with the gallery ID you wish to display. To create a new gallery, use the <a href="@link" target="_blank">Cincopa Wizard</a>.',
            array(
                '@example' => '[cincopa 10465673]',
                '@link' => 'http://www.cincopa.com/wpplugin/start.aspx'
            )
        );
    }
}

/**
 * Build HTML code part for replaced cincopa tag.
 * Is used as callback function for regex replacing,
 * and uses the theme_cincopa_callback function to
 * style the code and add required JS to page.
 *
 * @param array $match
 *   Matched with regex information.
 *
 * @return
 *   HTML elements formated string.
 *
 * @see theme_cincopa_callback()
 */
function cincopa_plugin_callback($match) {
  $unique = uniqid('');
  array_push($match, $unique);

  // Pass through theming function
  $return = theme('cincopa_callback', $match);
  
  return $return;
}

/**
 * Implements hook_theme().
 */
function cincopa_theme($existing, $type, $theme, $path) {
  return array(
    'cincopa_callback' => array(
      'variables' => array('match' => NULL)
    )
  );
}

/**
 * Theme callback function
 *
 * This function should replace the tag with an 
 * empty DIV, with a unique structure and ID, 
 * which is later replaced by the generated code 
 * using the added JS.
 *
 * NOTE: Input filter must not use caching for the 
 * JS to correctly be added to the page.
 *
 * @param array $match
 *  The requested gallery ID as set in the tag (in 
 *  position 0).
 *
 * @param $unique
 *  A unique id acting as JS selector.
 *
 * @see cincopa_plugin_callback()
 *
 * @ingroup themeable
 */
function theme_cincopa_callback($match) {
  // Add needed JavaScript library (make sure only loads once per page)
  static $added_cincopa_js = FALSE;
  if (!$added_cincopa_js) {
    drupal_add_js(
        '//www.cincopa.com/media-platform/runtime/libasync.js',
        array(
            'type' => 'external',
            'scope' => 'header',
            'weight' => -1,
            'cache' => FALSE,
            'preprocess' => FALSE,
        )
    );
    $added_cincopa_js = TRUE;
  }
  
  // Add specific JavaScript for this gallery
  drupal_add_js(
      'cp_load_widget("'.urlencode(check_plain($match[0])).'", "_cp_widget_'.$match[2].'");',
      array(
        'type' => 'inline',
        'scope' => 'footer',
        'cache' => FALSE,
        'preprocess' => FALSE,
      )
  );
  
  // Return the div which will turn into a gallery
  $return = '<div id="_cp_widget_' . $match[2] . '">...</div>';

  return $return;
}
